### ISSUE TITLE
uhh how do i download the keys?

### ISSUE THREAD

**Issue by pastel-n0va** [icosaswitch/Yuzu-NAND#4]

**Comment by AzzyC** [comment]
I just curled the raw file into a prod.keys file

Or you could open this link

https://raw.githubusercontent.com/icosaswitch/Yuzu-NAND/master/prod.keys

and save the page as a prod.keys file by hitting Ctrl + s

**Comment by pastel-n0va** [comment]
I already got them. thanks for not helping and forcing me to do it by myself.

**Comment by AzzyC** [comment]
> I already got them. thanks for not helping and forcing me to do it by myself.

I try to help and you spit in my face. you will have a long life ahead of you..

what can I do if this is how github is for downloading files
